src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="products")
     */
    private $categories;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Stock;

    public function __construct()
    {
        return $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Categories[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addProduct($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getStock(): ?bool
    {
        return $this->Stock;
    }

    public function setStock(bool $Stock): self
    {
        $this->Stock = $Stock;

        return $this;
    }
}

templates/elements/cart.html.twig
<div class="showCard text-center">
    <h3 class="mb-5">Your card</h3>
    <hr>
    {% for item in items %}
        <div class="itemCard col-sm mb-3">
            <p class="boldProductName">{{ item.product.name }}</p>
            <div class="quantity-cart-home mb-3">
                <div class="icon-cart imgCardLeft">
                    <a class="tokenImg aCard" href="{{ path('add_cart', {id : item.product.id}) }}"><img src="/img/plus.png" alt=""></a>
                </div>
                <div class="icon-cart tokenImg quantityCard">
                    {{ item.quantity }}
                </div>
                <div class="icon-cart imgCardRight">
                    <a class="tokenImg aCard" href="{{ path('remove_cart', {id : item.product.id}) }}"><img src="/img/minus.png" alt=""></a>
                </div>
            </div>

            <p> Price : {{ item.product.price * item.quantity}} $
            <a class="m-1 aCard" href="{{ path('delete_cart', {'id': item.product.id}) }}"><img src="\img\delete.png" alt=""></a>
            </p>
        </div>
        <hr>
    {% endfor %}
    <div class="col-sm mb-3">
        <h5>Total of card : </h5>
        <h4>{{ total | number_format(2, '.', ',') }} $</h4>
    </div>
    <a href="{{ path('order_index') }}" class="btn btn-primary order">Order</a>
</div>

templates/elements/product.html.twig
<div class="row">
    {% for product in products %}
        <div class="col-md-4">
            <div class="card bg-light mb-3">
                <div class="card-header text-center boldProductName">
                    {{product.name}}
                </div>

                <img src="/img/{{product.image}}" alt="">
                <div class="card-body text-center">
                    <p>{{product.description}}</p>
                </div>
                <div class="card-footer text-center">
                    {% if product.stock == true %}
                        <a class="btn btn-success btnCart aCard" href="{{ path('add_cart', { 'id' : product.id}) }}">Add to cart</a>
                    {% else %}
                        <button class="btn btn-danger btnCart" disabled>Out of Stock</button>
                    {% endif %}
                    <p class="mb-0 mt-2">{{product.price}} €</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>